FROM amazoncorretto:8
MAINTAINER lucascaceres
COPY /Portfolio/out/artifacts/Portfolio_jar/Portfolio.jar Portfolio.jar
ENTRYPOINT ["java","-jar","/Portfolio/out/artifacts/Portfolio_jar/Portfolio.jar Portfolio.jar"]